: HELLO ." Bonjour mon amour !" CR ;
: DOUBLE ( N ...2N ) DUP + ;
: FACT DUP 1  > IF DUP 1 - RECURSE * ELSE DROP 1 THEN ;  (  ceci est un commentaire  ) 
: POW DUP 0 = IF DROP 1 EXIT THEN 1 SWAP 0 DO OVER *  LOOP SWAP DROP ;
: FIBONACCI DUP 0 = IF DROP 0  EXIT THEN DUP 1 = IF DROP 1 EXIT THEN DUP 2 = IF DROP 1 EXIT THEN 1 1 ROT 2 - 0 DO OVER + SWAP LOOP DROP ;
: COUNTDOWN  10 BEGIN DUP . 1 - DUP 0 > WHILE REPEAT DROP DROP ;
: TUCK SWAP OVER ;
: 2DROP DROP DROP ;
: SUM_SQUARE  1 + 0  DO I + LOOP DUP * ;
: CUBE  DUP DUP * * ;
: SUM_CUBES 1 + 0  DO  I CUBE + LOOP ; 
: RECUNACCI 2 +  0  DO  I FIBONACCI  LOOP DROP ; 
: CAT 32 EMIT 32 EMIT 32 EMIT  47 EMIT 95 EMIT 47 EMIT 32 EMIT CR 40 EMIT 32 EMIT 111 EMIT 46 EMIT 111 EMIT 32 EMIT 41 EMIT CR 32 EMIT 32 EMIT 62 EMIT 32 EMIT 94 EMIT 32 EMIT 60 EMIT CR ;
: :D ." :D" ;
STRING SOURCE 
" https://github.com/cleobuline/some-c-sources/blob/main/forth_gmp_irc_bot.c " SOURCE ! 
: PGCD DUP 0 = IF DROP ELSE SWAP OVER MOD RECURSE THEN ;
: PRIME? DUP 2 < IF DROP 0 EXIT THEN DUP 2 = IF DROP 1 EXIT THEN DUP 2 MOD 0 = IF DROP 0 EXIT THEN DUP SQRT 3 DO DUP I MOD 0 = IF DROP 0 UNLOOP EXIT THEN 2 +LOOP DROP 1 ;
VARIABLE SEED  12345 SEED !  

 : RANDOM ( -- n ) SEED @ 1103515245 * 12345 + DUP SEED ! 2147483648 MOD ;

 : RAND  ( start stop -- result ) OVER - 1 + RANDOM OVER MOD SWAP DROP + ;
 : DICE  1 6 RAND ; 
 : ROLLDICES DICE DICE DICE .S FLUSH ; 
 : 2DUP OVER OVER ;
 :  3DUP  2 PICK 2 PICK 2  PICK ; 
 
CREATE NUMS 50 ALLOT
CREATE STARS 12 ALLOT
VARIABLE COUNT

: INIT-NUMS 0 DO I 1 + I NUMS ! LOOP 0 COUNT ! ;
: SHUFFLE-NUMS 1 DO 0 I RAND DUP NUMS @ I NUMS @ SWAP I NUMS ! OVER NUMS ! DROP LOOP ;
: PICK-NUM COUNT @ DUP 50 < IF NUMS @ COUNT @ 1 + COUNT ! ELSE DROP 1 THEN ;
: NUM-TO-STR DUP 10 < IF 48 + EMIT ELSE DUP 10 / RECURSE 10 MOD 48 + EMIT THEN ;
: INIT-STARS 12 0 DO I 1 + I STARS ! LOOP 0 COUNT ! ;
: SHUFFLE-STARS 12 1 DO 0 I RAND DUP STARS @ I STARS @ SWAP I STARS ! OVER STARS ! DROP LOOP ;
: PICK-STAR COUNT @ DUP 12 < IF STARS @ COUNT @ 1 + COUNT ! ELSE DROP 1 THEN ;

: LOTO 49 INIT-NUMS 49 SHUFFLE-NUMS 5 0 DO PICK-NUM DUP NUM-TO-STR 32 EMIT LOOP DROP 1 10 RAND DUP NUM-TO-STR DROP CR ;
: EURO 50 INIT-NUMS 50 SHUFFLE-NUMS 5 0 DO PICK-NUM DUP NUM-TO-STR 32 EMIT LOOP DROP INIT-STARS SHUFFLE-STARS PICK-STAR DUP NUM-TO-STR 32 EMIT DROP PICK-STAR DUP NUM-TO-STR DROP CR ;

LOAD "test2.fth"   
