: TRIPLE DUP DUP + + ;
5 DOUBLE TRIPLE CR .S
: TEST-CASE   CASE  1 OF  ." UN " CR  ENDOF 2 OF  ." DEUX " CR ENDOF 3 OF  ." TROIS "  CR ENDOF ." Others " CR  ENDCASE ;
5 TEST-CASE 
." MOTS DEFINI TRIPLE DOUBLE TEST_CASE " CR 
